<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>task_planner_fsm</name>
  <version>0.0.0</version>
  <description>TODO: Package description</description>
  <maintainer email="yeray.navarro@estudiantat.upc.edu">ynavarro@cdei.upc.edu</maintainer>
  <license>Apache-2.0</license>

  <exec_depend>ur_msgs</exec_depend>
  <exec_depend>std_srvs</exec_depend>
  <exec_depend>rcl_interfaces</exec_depend>
  <exec_depend>navi_wall</exec_depend>
  <exec_depend>tf2_geometry_msgs</exec_depend>
  <exec_depend>arm_control</exec_depend>

  <test_depend>ament_copyright</test_depend>
  <test_depend>ament_flake8</test_depend>
  <test_depend>ament_pep257</test_depend>
  <test_depend>python3-pytest</test_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
